### ISSUE TITLE
I think the plugin needs to add clearFix on the parent element.

### ISSUE THREAD

**Issue by devonmather** [emn178/jquery-stickit#7]
The sidebar element wasn't showing up once it stuck in Chrome on Mac. To solve the issue I added a class of clearFix to the parent element, code attached.

````css
.clearFix::after {
	clear: both;
	display: block;
	content: ' ';
	visibility: hidden;
	line-height: 0;
	height: 0;
}
```
